### ISSUE TITLE
Voronoi pointer unfreeable

### ISSUE THREAD

**Issue by patatattak** [fabanc/SharpBoostVoronoi#3]
Hi Fabien,

I tried your c# wrapper for boost voronoi and I get an issue : 
I can't free the memory allocation used by v* in the VoronoiWrapper class.

My program creates many instances of VoronoiWrapper, but when I delete them or reinit them, the c++ mem allocation doesn't empty.
So i get my memory usage increasing up and up...

I'm quite a newbie, and I am not able to compile DLL, but if you have time to add a public method in the DLL to free up v*, it would be nice !

Patatattak

**Comment by patatattak** [comment]
mmmm

Finally, it seems my memory problem comes from another thing...

**Comment by patatattak** [comment]
But I still can't free the BoostVoronoi object.
It seems that the Garbage Collector doesn't clean, even if unused.

**Comment by fabanc** [comment]
Thanks for the feedback

I will have a look at this week. I am rolling out another project so that's going to be as time permits, but I should be able to investigate that. I'll implement that method if that's what is needed. Are you using a specific release of the or the latest from the master branch?

**Comment by fabanc** [comment]
I may have to provide a wrapper for the method clear as well before removing references to anything. The C++ Voronoi Builder exposes that as explained here [http://www.boost.org/doc/libs/1_63_0/libs/polygon/doc/voronoi_builder.htm]

I have done a quick attempt but the when called from the C# code, Clear() returns a stack overflow exception so I will resume that ASAP this week.

**Comment by patatattak** [comment]
> Are you using a specific release of the or the latest from the master branch?

I'm using the x64 versions of your DLLs, downloaded here in the master branch.

**Comment by fabanc** [comment]
Noted. I have added a Clear() method. It does get rid of everything that the CLI wrapper generates, however it does not seem to remove the previously generated data in the core C++ components. Nothing seem to be available for that. It does not solve the problem of removing the reference to v*. I will have a look at that next.

**Comment by fabanc** [comment]
I have forced the C++ wrapper to implement a destructor and have it remove the reference to the core C++ object. The C# wrapper now implement the IDisposable interface. I need more testing to make sure it is working well and optimized but since I won't be able to look at it until this week end, the latest code has been updated in case you want to give it a shot.

`            using (BoostVoronoi bv = new BoostVoronoi())
            {
                    //Do stuffs
            } //Getting out of scope will call the Dispose method and free resources.
`

**Comment by fabanc** [comment]
Got some extra time that allowed me to finish earlier than expected. Issue closed. The documentation has been updated.

**Comment by patatattak** [comment]
Thanx, man, I'll test that !

**Comment by patatattak** [comment]
It works.
I can now create many instances, Dispose() method clear cleanly memory.
Thanks a lot.

**Comment by fabanc** [comment]
Perfect. I have also created a new release with this change. Any release starting from 1.0.3 will have that fix incorporated.
